import IndustryIcon from "../assets/icons/industry.png";
import GearIcon from "../assets/icons/gear.png";
import SettingsPurple from "../assets/icons/settings-purple.png";
import SettingsGreen from "../assets/icons/settings-green.png";
import AlertIcon from "../assets/icons/alert.png";

export const stats = [
  {title: "Total Machines", value: "12", icon: IndustryIcon},
  {title: "Operational Machines", value: "09", icon: SettingsPurple},
  {
    title: "Machines in Warning",
    value: "3",
    icon: GearIcon,
    statusIndicator: {type: "dot", color: "orange"},
  },
  {
    title: "Critical Machines",
    value: "5",
    icon: AlertIcon,
    statusIndicator: {type: "dot", color: "red"},
  },
  {
    title: "Average Utilization",
    value: "78%",
    icon: SettingsGreen,
    statusIndicator: {type: "arrow", color: "green"},
  },
];

export const allMachines = [
  {
    id: "M-101",
    name: "CNC Lathe Alpha",
    status: "Operational",
    plant: "Titan Foundry",
    utilization: "85",
    lastMaintenance: "02 Apr, 2025",
    scheduledMaintenance: "02 Jul, 2025",
    outputEfficiency: "88",
    downtime: "4h 12m",
    digitalTwin: "Active",
    issueFlag: "NA",
  },
  {
    id: "M-109",
    name: "Laser Cutter XMark",
    status: "Warning",
    plant: "Titan Foundry",
    utilization: "63",
    lastMaintenance: "30 Mar, 2025",
    scheduledMaintenance: "29 Jun, 2025",
    outputEfficiency: "70",
    downtime: "12h 45m",
    digitalTwin: "Active",
    issueFlag: "Vibration",
  },
  {
    id: "M-104",
    name: "Hydraulic Press H-3",
    status: "Critical",
    plant: "Nova Steel Works",
    utilization: "42",
    lastMaintenance: "25 Mar, 2025",
    scheduledMaintenance: "25 Apr, 2025",
    outputEfficiency: "48",
    downtime: "28h 30m",
    digitalTwin: "Inactive",
    issueFlag: "Oil Leak",
  },
  {
    id: "M-115",
    name: "Packaging SensorBot",
    status: "Operational",
    plant: "Orion Plastics",
    utilization: "91",
    lastMaintenance: "05 Apr, 2025",
    scheduledMaintenance: "05 Jul, 2025",
    outputEfficiency: "94",
    downtime: "2h 10m",
    digitalTwin: "Active",
    issueFlag: "NA",
  },
  {
    id: "M-112",
    name: "Welding Unit Pro 5",
    status: "Warning",
    plant: "Vega Components",
    utilization: "70",
    lastMaintenance: "28 Mar, 2025",
    scheduledMaintenance: "28 Jun, 2025",
    outputEfficiency: "73",
    downtime: "8h 20m",
    digitalTwin: "Active",
    issueFlag: "Over Heat",
  },
  {
    id: "M-102",
    name: "Conveyor Belt CX-3",
    status: "Operational",
    plant: "Titan Foundry",
    utilization: "82",
    lastMaintenance: "30 Mar, 2025",
    scheduledMaintenance: "30 Jun, 2025",
    outputEfficiency: "85",
    downtime: "5h 45m",
    digitalTwin: "Active",
    issueFlag: "NA",
  },
  {
    id: "M-108",
    name: "Milling Machine Delta",
    status: "Warning",
    plant: "Nova Steel Works",
    utilization: "68",
    lastMaintenance: "26 Apr, 2025",
    scheduledMaintenance: "26 Jul, 2025",
    outputEfficiency: "72",
    downtime: "9h 15m",
    digitalTwin: "Active",
    issueFlag: "Spindle Wear",
  },
  {
    id: "M-121",
    name: "3D Printer Jetform",
    status: "Operational",
    plant: "Orion Plastics",
    utilization: "88",
    lastMaintenance: "06 Apr, 2025",
    scheduledMaintenance: "06 Jul, 2025",
    outputEfficiency: "90",
    downtime: "3h 40m",
    digitalTwin: "Active",
    issueFlag: "NA",
  },
  {
    id: "M-119",
    name: "Robotic Arm X-7",
    status: "Critical",
    plant: "Zenith Engineering",
    utilization: "50",
    lastMaintenance: "24 Mar, 2025",
    scheduledMaintenance: "24 Apr, 2025",
    outputEfficiency: "55",
    downtime: "22h 10m",
    digitalTwin: "Inactive",
    issueFlag: "Joint Failure",
  },
  {
    id: "M-113",
    name: "Paint Booth PX-200",
    status: "Operational",
    plant: "Vega Components",
    utilization: "77",
    lastMaintenance: "30 Mar, 2025",
    scheduledMaintenance: "30 Jun, 2025",
    outputEfficiency: "80",
    downtime: "6h 30m",
    digitalTwin: "Active",
    issueFlag: "NA",
  },
];


export const machineMaintenanceTable = [
  {
    alertType: "Temp Strike",
    riskLevel: "High",
    suggestedAction: "Schedule Immediate Maintenance",
  },
  {
    alertType: "Overheating Detected",
    riskLevel: "High",
    suggestedAction: "Reduce Load & Inspect Fan System",
  },
  {
    alertType: "Predictive Part Failure",
    riskLevel: "Medium",
    suggestedAction: "Pre-order Replacement Part",
  },
  {
    alertType: "Power Fluctuation Pattern",
    riskLevel: "High",
    suggestedAction: "Monitor Continuously",
  },
];