import DashboardIcon from "@/assets/icons/dashboard-icon.png";
import IndustryIcon from "@/assets/icons/industry.png";
import FinanceIcon from "@/assets/icons/finance.png";
import GearIcon from "@/assets/icons/gear.png";
import SettingsIcon from "@/assets/icons/settings.png";

export  const plantStats = [
  {title: "Total plants", value: "12", icon: IndustryIcon},
  {title: "Operational Plants", value: "09", icon: SettingsIcon},
  {title: "Under Maintenance", value: "3", icon: GearIcon, statusIndicator: { type: "dot", color: "orange" }},
  {title: "Overall OEE", value: "89.3%", icon: DashboardIcon, statusIndicator: { type: "arrow", color: "green" }},
  {title: "Budget Deviation", value: "+ $12,400", icon: FinanceIcon, statusIndicator: { type: "arrow", color: "red" }},
];

export const allPlants = [
    {
      id: 1,
      name: "Orion Plant",
      machine: 65,
      labour: 48,
      oee: 88.3,
      downtime: "1h 15m",
      lastActivity: "1 hr ago",
      financialStatus: "+$4,250",
      financialTrend: "up",
    },
    {
      id: 2,
      name: "Zephyr Works",
      machine: 74,
      labour: 53,
      oee: 81.9,
      downtime: "2h 10m",
      lastActivity: "30 min ago",
      financialStatus: "-$3,700",
      financialTrend: "down",
    },
    {
      id: 3,
      name: "Phoenix Factory",
      machine: 58,
      labour: 42,
      oee: 86.5,
      downtime: "45m",
      lastActivity: "2 hrs ago",
      financialStatus: "+$5,800",
      financialTrend: "up",
    },
    {
      id: 4,
      name: "Atlas Production",
      machine: 80,
      labour: 62,
      oee: 90.2,
      downtime: "30m",
      lastActivity: "15 min ago",
      financialStatus: "+$8,200",
      financialTrend: "up",
    },
    {
      id: 5,
      name: "Nova Manufacturing",
      machine: 45,
      labour: 38,
      oee: 78.6,
      downtime: "3h 20m",
      lastActivity: "4 hrs ago",
      financialStatus: "-$2,900",
      financialTrend: "down",
    },
    {
      id: 6, 
      name: "Helios Industries",
      machine: 70,
      labour: 55,
      oee: 89.1,
      downtime: "50m",
      lastActivity: "1 hr ago",
      financialStatus: "+$6,300",
      financialTrend: "up",
    },
    {
      id: 7,
      name: "Zenith Works",
      machine: 62,
      labour: 47,
      oee: 84.3,
      downtime: "1h 40m",
      lastActivity: "2 hrs ago",
      financialStatus: "+$3,100",
      financialTrend: "up",
    },
    {
      id: 8,
      name: "Titan Plant",
      machine: 55,
      labour: 40,
      oee: 79.8,
      downtime: "2h 30m",
      lastActivity: "3 hrs ago",
      financialStatus: "-$4,500",
      financialTrend: "down",
    },
    {
      id: 9,
      name: "Solaris Factory",
      machine: 68,
      labour: 52,
      oee: 87.4,
      downtime: "55m",
      lastActivity: "45 min ago",
      financialStatus: "+$5,200",
      financialTrend: "up",
    },
    {
      id: 10,
      name: "Mercury Production",
      machine: 53,
      labour: 39,
      oee: 80.5,
      downtime: "1h 55m",
      lastActivity: "2.5 hrs ago",
      financialStatus: "-$1,800",
      financialTrend: "down",
    },
    {
      id: 11,
      name: "Neptune Industries",
      machine: 72,
      labour: 58,
      oee: 88.9,
      downtime: "40m",
      lastActivity: "1.5 hrs ago",
      financialStatus: "+$7,100",
      financialTrend: "up",
    },
    {
      id: 12,
      name: "Jupiter Manufacturing",
      machine: 63,
      labour: 45,
      oee: 83.7,
      downtime: "1h 25m",
      lastActivity: "50 min ago",
      financialStatus: "+$4,900",
      financialTrend: "up",
    }
  ];