import taskIcon from "@/assets/icons/task.svg";
import RightTickIcon from "@/assets/icons/right-tick.svg";
import InProgressIcon from "@/assets/icons/in-progress.svg";
import PendingIcon from "@/assets/icons/pending.svg";
import OverdueIcon from "@/assets/icons/overdue.svg";

export const taskOverview = [
  {title: "Total Tasks", value: "312", icon: taskIcon},
  {title: "Completed", value: "225", icon: RightTickIcon},
  {title: "In Progress", value: "61", icon: InProgressIcon},
  {
    title: "Pending",
    value: "18",
    icon: PendingIcon,
    statusIndicator: {type: "dot", color: "orange"},
  },
  {
    title: "Overdue",
    value: "7",
    icon: OverdueIcon,
    statusIndicator: {type: "dot", color: "red"},
  },
];

export const task = [
  {
    id: "T-0148",
    taskName: "CNC Routine Check",
    assignedTo: "Rakesh S",
    plant: "Orion Precision Works",
    status: "In Progress",
    priority: "High",
    dueDate: "11 Apr, 2025",
    createdBy: "Floor Supervisor",
  },
  {
    id: "T-0151",
    taskName: "Conveyor Belt Fix",
    assignedTo: "Manoj P",
    plant: "Titan Foundry",
    status: "Pending",
    priority: "Medium",
    dueDate: "10 Apr, 2025",
    createdBy: "Maintenance Lead",
  },
  {
    id: "T-0154",
    taskName: "Clean Work Area",
    assignedTo: "Ritu M",
    plant: "Nova Steel Works",
    status: "Completed",
    priority: "Low",
    dueDate: "09 Apr, 2025",
    createdBy: "Shift Manager",
  },
  {
    id: "T-0156",
    taskName: "QA Check – Lot B",
    assignedTo: "Sita V",
    plant: "Stellar CastTech",
    status: "In Progress",
    priority: "High",
    dueDate: "11 Apr, 2025",
    createdBy: "QA Manager",
  },
  {
    id: "T-0159",
    taskName: "Oil Refill (Lathe 2)",
    assignedTo: "Alok M",
    plant: "Titan Foundry",
    status: "Completed",
    priority: "Medium",
    dueDate: "09 Apr, 2025",
    createdBy: "Maintenance Lead",
  },
  {
    id: "T-016",
    taskName: "Packing Material Audit",
    assignedTo: "Anita D",
    plant: "Nova Steel Works",
    status: "Pending",
    priority: "Low",
    dueDate: "12 Apr, 2025",
    createdBy: "Inventory Manager",
  },
  {
    id: "T-0162",
    taskName: "Emergency Stop Repair",
    assignedTo: "Sunil C",
    plant: "Orion Precision Works",
    status: "In Progress",
    priority: "High",
    dueDate: "10 Apr, 2025",
    createdBy: "Floor Supervisor",
  },
  {
    id: "T-0163",
    taskName: "Lubrication Check",
    assignedTo: "Pooja N",
    plant: "Titan Foundry",
    status: "Completed",
    priority: "Low",
    dueDate: "08 Apr, 2025",
    createdBy: "Maintenance Lead",
  },
  {
    id: "T-0164",
    taskName: "Inventory Reconciliation",
    assignedTo: "Rahul J",
    plant: "Stellar CastTech",
    status: "Pending",
    priority: "Medium",
    dueDate: "11 Apr, 2025",
    createdBy: "QA Manager",
  },
  {
    id: "T-0165",
    taskName: "Raw Material Dispatch",
    assignedTo: "Vikram S",
    plant: "Nova Steel Works",
    status: "In Progress",
    priority: "High",
    dueDate: "10 Apr, 2025",
    createdBy: "Inventory Manager",
  },
];
